name: API Testing and Reports

on:
  push:
    paths:
      - 'projects/api_testing/**'
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Load repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          cd projects
          pip install -r api_testing/requirements.txt

      - name: Run pytest and generate reports
        run: |
          cd projects
          python -m pytest api_testing/tests --html=api_testing/reports/report.html --self-contained-html --alluredir=api_testing/reports/allure-results

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: projects/api_testing/reports/