name: OOP Python Project Test and Reports Automation Workflow

on:
  push:
    paths:
      - 'projects/oop_python/**'
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Load repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          cd projects
          pip install -r oop_python/requirements.txt

      - name: Run pytest and generate reports
        run: |
          cd projects
          python -m pytest oop_python/tests --html=oop_python/reports/report.html --self-contained-html --alluredir=oop_python/reports/allure-results

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: projects/oop_python/reports/